### PR TITLE
CM-939 docs

### PR DESCRIPTION
**Pull request by danmash**
I've updated docs for the convo edit endpoint based on my changes

### CODE REVIEW

**Review by rodriguesk — COMMENTED** [review]
I defer to @cyplas for this review.

**Review by cyplas — APPROVED** [review]

**Comment by rodriguesk** [comment]
@danmash you can merge this once you’ve adding in the things Cyprian suggested.

**Comment by danmash** [comment]
@rodriguesk @cyplas 

> 
> make it clear in the description that it's not mandatory to include all the fields

done

> either include the response body or point the user to another endpoint which uses the same response body

I didn't get this, there are response body

**Comment by rodriguesk** [comment]
@danmash maybe he means for the 400 response? 
C7CE3954-1388-42A2-AAAE-A17FFFD73B6A
A656C73B-7096-4A04-AEB9-BFB071A933B0

**Comment by danmash** [comment]
but the response contains only `message` field which already listed there

**Comment by rodriguesk** [comment]
Then sounds like you’ve done everything he suggested!

**Pull request merged**
