### PR TITLE
CM-1046 pytest job added to circleci

### PR DESCRIPTION
**Pull request by danmash**

### CODE REVIEW

**Review by rodriguesk — APPROVED** [review]

**Comment by danmash** [comment]
I need to create a new docker-compose file to optimize this.

**Comment by danmash** [comment]
@rodriguesk I've updated the branch according to your recent changes, please double-check

**Comment by danmash** [comment]
the only difference here that you have to use `-p climatemind-backend` to specify the project and add folder `docker` before `docker/docker-compose.yml`

**Review by rodriguesk — APPROVED** [review]
Looks good. Has documentation for how to spin up and should be okay for migrations theoretically.

**Pull request merged**
