### PR TITLE
 #396: replaced login cypress test with pytest test

### PR DESCRIPTION
**Pull request by cyplas**
### Detailed information:

Replaces the cypress e2e login test with an equivalent pytest one.
Except for not covering the limiter stuff, as discussed in #396. I recommend creating a separate issue for that.

### Closing issues: 

List all issues the pull request solve: 

- *#396*h

### Test plan (required)

- [X] The PR contains new PyTest unit/integration tests for any function or functional added. 
- [X] The PR changes existing PyTest unit/integration tests to keep all tests up to date.
- [X] The PR does not lead to degradation in unit test coverage.
- [X] Project parts affected by changes in this PR was tested manually on your local (using Postman or in any other way). List everything you've tested below:
  - app/auth/tests/test_auth_routes.py

### CODE REVIEW

**Comment by cyplas** [comment]
@danmash Hmm, this is odd. The black linter clears for me locally without changes, but here it complains about 10 different files, only one of which I've even changed. Not sure what I'm missing here ...

**Comment by cyplas** [comment]
And I forgot to mention that I noticed something strange with the recaptcha: any string value seems to be fine. Or, if that's actually expected somehow, then I'm not sure why the cypress test had a long key-looking value in there.

**Comment by danmash** [comment]
@cyplas 
@Svenstar74 faced a similar issue. 
I guess he installed the fresh black version and it works fine. Correct me if I'm wrong. 
@cyplas Try to update black.

**Comment by cyplas** [comment]
> @cyplas @Svenstar74 faced a similar issue. I guess he installed the fresh black version and it works fine. Correct me if I'm wrong. @cyplas Try to update black.

Aha, indeed. Thanks!

**Review by danmash — APPROVED** [review]
Awesome, thanks!

**Comment by danmash** [comment]
👍

**Pull request merged**
