### PR TITLE
Cm240 task 272 localise impacts

### PR DESCRIPTION
**Pull request by rodriguesk**

### CODE REVIEW

**Comment by rodriguesk** [comment]
@y-himanen Please test the code works for when there is no zip code available! Thanks! I still need to check that the recursion function is working properly but this PR is just to get the pipeline set up, even if it has bugs.

**Comment by y-himanen** [comment]
Not 100% sure what all you wanted me to test, but ran it through postman without a postal code:
```
172.19.0.1 - - [09/Jan/2021 13:24:41] "POST /scores HTTP/1.1" 201 -
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
> /app/knowledge_graph/score_nodes.py(229)get_is_possibly_local()
-> return node["isPossiblyLocal"]
```
```
172.19.0.1 - - [09/Jan/2021 13:29:42] "GET /feed?session-id=fd76bd78-d2bd-4db1-9341-f236fa1e0ec9 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/knowledge_graph/routes.py", line 336, in get_feed
    feed_entries = get_feed_results(session_id, N_FEED_CARDS)
  File "/usr/local/lib/python3.8/site-packages/flask_caching/__init__.py", line 907, in decorated_function
    rv = f(*args, **kwargs)
  File "/app/knowledge_graph/routes.py", line 359, in get_feed_results
    recommended_nodes = get_user_nodes(scores, N_FEED_CARDS, session_id)
  File "/app/knowledge_graph/score_nodes.py", line 352, in get_user_nodes
    climate_effects = simple_scoring(G, user_scores, session_id)
  File "/app/knowledge_graph/score_nodes.py", line 290, in simple_scoring
    "isPossiblyLocal": get_is_possibly_local(localised_acyclic_graph[node]),
  File "/app/knowledge_graph/score_nodes.py", line 229, in get_is_possibly_local
    return node["isPossiblyLocal"]
  File "/usr/local/lib/python3.8/site-packages/networkx/classes/coreviews.py", line 54, in __getitem__
    return self._atlas[key]
KeyError: 'isPossiblyLocal'
```

**Comment by rodriguesk** [comment]
@y-himanen ready for your review again.

**Review by y-himanen — APPROVED** [review]
tested both with and without zipcodes

**Review by y-himanen — CHANGES_REQUESTED** [review]
remove breakpoint on line 428 in make_graph

**Pull request merged**
