### PR TITLE
adding finalised draft

### PR DESCRIPTION
**Pull request by Expan75**
Hey ya guys!

Here's the final draft. It does not include beautification standards except for PEP8 but I guess we can just add it in later :)

### CODE REVIEW

**Review by rodriguesk — CHANGES_REQUESTED** [review]
Great job! I think the only thing is that we want the team member who did the pull request to do merge to master after getting a passing review (instead of me). For people not on the team who do a PR, their contribution would be merged by someone on the team. And that reviews should happen within 7 days of request to prevent the PR drifting too far away from current state of master.

After fixing this rerequest review.

**Review by biotom — APPROVED** [review]

**Comment by biotom** [comment]
@Expan75 should this be merged into master?

**Comment by rodriguesk** [comment]
I requested changes that have to be made before merge can happen. @Expan75 @biotom

**Comment by rodriguesk** [comment]
I'm merging this, but @Expan75. In future, the PR requester is the one who should merged when it gets approved.

**Pull request merged**
