### PR TITLE
393 replace cypress email tests with pytest and eliminate cypress

### PR DESCRIPTION
**Pull request by cyplas**
### Detailed information:

Replaced the cypress email e2e tests with pytest integration tests, as for the other e2e tests, and got rid of remaining cypress stuff in general.

### Closing issues: 

List all issues the pull request solve: 

- *#393*
- *#406*

### Test plan (required)

- [X] The PR contains new PyTest unit/integration tests for any function or functional added. 
- [X] The PR changes existing PyTest unit/integration tests to keep all tests up to date.
- [X] The PR does not lead to degradation in unit test coverage.
- [X] Project parts affected by changes in this PR was tested manually on your local (using Postman or in any other way). List everything you've tested below:
  - pytest

### CODE REVIEW

**Comment by cyplas** [comment]
@danmash Not surprisingly this PR is not passing the circleci cypress check. I'm guessing that the webhook just needs to be deleted (https://github.com/ClimateMind/climatemind-backend/settings/hooks), but I haven't used these before and don't want to make a mess. :)

**Comment by cyplas** [comment]
Also, I upgraded `black` (due to the otherwise failing lint test) and its dependencies `click` and `packaging`, but I see that `click` is also explicitly used in ontology processing: https://github.com/ClimateMind/climatemind-backend/blob/develop/app/ontology/commands/process_owl.py#L3.

**Comment by cyplas** [comment]
And I also wonder about [config.yml](https://github.com/ClimateMind/climatemind-backend/pull/490/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47). I removed clearly cypress stuff, but I suspect that more could be removed (e.g., node), though I'm not sure how to test.

**Review by danmash — APPROVED** [review]

**Comment by danmash** [comment]
@cyplas Awesome work on this! It was a long way and you did it, congratulations 🎉 
Also, I would like to thank @brianpeiris who worked on this milestone. 
Thank you guys 👍

**Pull request merged**
